; overworld sprites
; SpriteSheetPointerTable indexes (see data/sprites/sprites.asm)
	const_def
	const SPRITE_BALLOT       ; $00
	const SPRITE_SNOWY        ; $01
	const SPRITE_BUCK         ; $02
	const SPRITE_BEATTRO      ; $03
	const SPRITE_NINA         ; $04
	const SPRITE_ELECTREEP    ; $05
	const SPRITE_CLAUDE       ; $06
	const SPRITE_CHROMANIX    ; $07
	const SPRITE_HELEN        ; $08
	const SPRITE_MERLITH      ; $09
	const SPRITE_LANTE        ; $0a
	const SPRITE_MUSERODE     ; $0b
	const SPRITE_RANDT        ; $0c
	const SPRITE_SIGNALITON   ; $0d
	const SPRITE_MITT         ; $0e
	const SPRITE_DRAWVILE     ; $0f
	const SPRITE_BLADEBERUS   ; $10
	const SPRITE_SAYA         ; $11
	const SPRITE_BOY          ; $12
	const SPRITE_GIRL         ; $13
	const SPRITE_14           ; $14
	const SPRITE_15           ; $15
	const SPRITE_16           ; $16
	const SPRITE_17           ; $17
	const SPRITE_18           ; $18
	const SPRITE_19           ; $19
	const SPRITE_1A           ; $1a
	const SPRITE_1B           ; $1b
	const SPRITE_1C           ; $1c
	const SPRITE_1D           ; $1d
	const SPRITE_1E           ; $1e
	const SPRITE_1F           ; $1f
	const SPRITE_20           ; $20
	const SPRITE_21           ; $21
	const SPRITE_22           ; $22
	const SPRITE_23           ; $23
	const SPRITE_24           ; $24
	const SPRITE_25           ; $25
	const SPRITE_26           ; $26
	const SPRITE_27           ; $27
	const SPRITE_28           ; $28
	const SPRITE_29           ; $29
	const SPRITE_2A           ; $2a
	const SPRITE_2B           ; $2b
	const SPRITE_2C           ; $2c
	const SPRITE_2D           ; $2d
	const SPRITE_2E           ; $2e
	const SPRITE_2F           ; $2f
	const SPRITE_30           ; $30
	const SPRITE_31           ; $31
	const SPRITE_32           ; $32
	const SPRITE_33           ; $33
	const SPRITE_34           ; $34
	const SPRITE_35           ; $35
	const SPRITE_36           ; $36
	const SPRITE_37           ; $37
	const SPRITE_38           ; $38
	const SPRITE_39           ; $39
	const SPRITE_3A           ; $3a
	const SPRITE_3B           ; $3b
	const SPRITE_3C           ; $3c
	const SPRITE_3D           ; $3d
	const SPRITE_3E           ; $3e
	const SPRITE_3F           ; $3f
	const SPRITE_40           ; $40
	const SPRITE_41           ; $41
	const SPRITE_42           ; $42
	const SPRITE_43           ; $43
	const SPRITE_44           ; $44
	const SPRITE_45           ; $45
	const SPRITE_46           ; $46
	const SPRITE_47           ; $47
	const SPRITE_48           ; $48
	const SPRITE_49           ; $49
	const SPRITE_4A           ; $4a
	const SPRITE_4B           ; $4b
	const SPRITE_4C           ; $4c
	const SPRITE_4D           ; $4d
	const SPRITE_4E           ; $4e
	const SPRITE_4F           ; $4f
	const SPRITE_50           ; $50
	const SPRITE_51           ; $51
	const SPRITE_52           ; $52
	const SPRITE_53           ; $53
	const SPRITE_54           ; $54
	const SPRITE_55           ; $55
	const SPRITE_56           ; $56
	const SPRITE_57           ; $57
	const SPRITE_58           ; $58
	const SPRITE_59           ; $59
	const SPRITE_5A           ; $5a
	const SPRITE_5B           ; $5b
	const SPRITE_5C           ; $5c
	const SPRITE_5D           ; $5d
	const SPRITE_5E           ; $5e
	const SPRITE_5F           ; $5f
	const SPRITE_60           ; $60
	const SPRITE_61           ; $61
	const SPRITE_62           ; $62
	const SPRITE_63           ; $63
	const SPRITE_64           ; $64
	const SPRITE_65           ; $65
	const SPRITE_66           ; $66
	const SPRITE_67           ; $67
	const SPRITE_68           ; $68
	const SPRITE_69           ; $69
	const SPRITE_6A           ; $6a
	const SPRITE_6B           ; $6b
	const SPRITE_6C           ; $6c
	const SPRITE_6D           ; $6d
	const SPRITE_6E           ; $6e
	const SPRITE_6F           ; $6f
	const SPRITE_70           ; $70
	const SPRITE_71           ; $71
	const SPRITE_72           ; $72
	const SPRITE_73           ; $73
	const SPRITE_74           ; $74
	const SPRITE_75           ; $75
	const SPRITE_76           ; $76
