NEWCHARMAP english
	charmap " ", $00
	charmap "A", $01
	charmap "B", $02
	charmap "C", $03
	charmap "D", $04
	charmap "E", $05
	charmap "F", $06
	charmap "G", $07
	charmap "H", $08
	charmap "I", $09
	charmap "J", $0a
	charmap "K", $0b
	charmap "L", $0c
	charmap "M", $0d
	charmap "N", $0e
	charmap "O", $0f
	charmap "P", $10
	charmap "Q", $11
	charmap "R", $12
	charmap "S", $13
	charmap "T", $14
	charmap "U", $15
	charmap "V", $16
	charmap "W", $17
	charmap "X", $18
	charmap "Y", $19
	charmap "Z", $1a
	charmap "(", $1b
	charmap ")", $1c
	charmap ":", $1d
	charmap ";", $1e
	charmap "[", $1f
	charmap "]", $20
	charmap "a", $21
	charmap "b", $22
	charmap "c", $23
	charmap "d", $24
	charmap "e", $25
	charmap "f", $26
	charmap "g", $27
	charmap "h", $28
	charmap "i", $29
	charmap "j", $2a
	charmap "k", $2b
	charmap "l", $2c
	charmap "m", $2d
	charmap "n", $2e
	charmap "o", $2f
	charmap "p", $30
	charmap "q", $31
	charmap "r", $32
	charmap "s", $33
	charmap "t", $34
	charmap "u", $35
	charmap "v", $36
	charmap "w", $37
	charmap "x", $38
	charmap "y", $39
	charmap "z", $3a
	charmap "'d", $3b
	charmap "'l", $3c
	charmap "'s", $3d
	charmap "'t", $3e
	charmap "'v", $3f

	charmap "0", $40
	charmap "1", $41
	charmap "2", $42
	charmap "3", $43
	charmap "4", $44
	charmap "5", $45
	charmap "6", $46
	charmap "7", $47
	charmap "8", $48
	charmap "9", $49

	charmap "?", $4a
	charmap "!", $4b
	charmap ".", $4d
	charmap "/", $4e
	charmap ",", $4f

	charmap "↑", $50
	charmap "→", $51
	charmap "↓", $52
	charmap "←", $53
	charmap "¥", $54

	charmap "⋯", $84
	charmap "...", $84
	charmap "~", $85
	charmap "-", $86
	charmap "α", $87
	charmap "'r", $88
	charmap "'m", $89
	charmap "'e", $8a
	charmap "'a", $8b
	charmap "'", $8c

; european
	charmap "ç", $8d
	charmap "é", $8e
	charmap "â", $8f
	charmap "ê", $90
	charmap "î", $91
	charmap "ô", $92
	charmap "û", $93
	charmap "à", $94
	charmap "è", $95
	charmap "ì", $96
	charmap "ò", $97
	charmap "ù", $98
	charmap "ë", $99
	charmap "ï", $9a
	charmap "ü", $9b

; extra contractions
	charmap "'i", $9c
	charmap "'o", $9d
	charmap "'u", $9e

; EVEN MORE contractions!
	charmap "'é", $9f
	charmap "'â", $a0
	charmap "'ê", $a1
	charmap "'î", $a2
	charmap "'ô", $a3
	charmap "'û", $a4
	charmap "'à", $a5
	charmap "'è", $a6
	charmap "'ì", $a7
	charmap "'ò", $a8
	charmap "'ù", $a9
	charmap "'ë", $aa
	charmap "'ï", $ab
	charmap "'ü", $a



; r o b o t
	charmap "Ａ", $55
	charmap "Ｂ", $56
	charmap "Ｃ", $57
	charmap "Ｄ", $58
	charmap "Ｅ", $59
	charmap "Ｆ", $5a
	charmap "Ｇ", $5b
	charmap "Ｈ", $5c
	charmap "Ｉ", $5d
	charmap "Ｊ", $5e
	charmap "Ｋ", $5f
	charmap "Ｌ", $60
	charmap "Ｍ", $61
	charmap "Ｎ", $62
	charmap "Ｏ", $63
	charmap "Ｐ", $64
	charmap "Ｑ", $65
	charmap "Ｒ", $66
	charmap "Ｓ", $67
	charmap "Ｔ", $68
	charmap "Ｕ", $69
	charmap "Ｖ", $6a
	charmap "Ｗ", $6b
	charmap "Ｘ", $6c
	charmap "Ｙ", $6d
	charmap "Ｚ", $6e
	charmap "０", $6f
	charmap "１", $70
	charmap "２", $71
	charmap "３", $72
	charmap "４", $73
	charmap "５", $74
	charmap "６", $75
	charmap "７", $76
	charmap "８", $77
	charmap "９", $78
	charmap "！", $79
	charmap "？", $7a
	charmap "＇", $7b
	charmap "，", $7c
	charmap "－", $86
	charmap "．", $4d
