MeteorCutscene_Text1:
    ramcoord $01, $08 ; string placement <X> <Y>
          ;XXXXXXXXXXXXXXXXXXXX
    text2 "[J'aurais dû m'en"
    line  "douter.["
    done

MeteorCutscene_Text2:
    ramcoord $01, $06
          ;XXXXXXXXXXXXXXXXXXXX
    text2 "C'est la dernière"
    line  "chose qu'a dit"
    line  "papa,"
    done

MeteorCutscene_Text3:
    ramcoord $01, $07
          ;XXXXXXXXXXXXXXXXXXXX
    text2 "avant de partir en"
    line  "courant..."
    done

MeteorCutscene_Text4:
    ramcoord $01, $08 ; string placement <X> <Y>
          ;XXXXXXXXXXXXXXXXXXXX
    text2 "Le matin suivant..."
    done

MeteorCutscene_Text5:
    ramcoord $01, $07
          ;XXXXXXXXXXXXXXXXXXXX
    text2 "l'observatoire"
    line  "était en ruines."
    done

MeteorCutscene_Text6:
    ramcoord $01, $07
          ;XXXXXXXXXXXXXXXXXXXX
    text2 "Personne ne sait"
    line  "vraiment ce qui"
    line  "s'est passé,"
    done

MeteorCutscene_Text7:
    ramcoord $01, $07
          ;XXXXXXXXXXXXXXXXXXXX
    text2 "et personne n'a"
    line  "revu mon père"
    line  "depuis."
    done

MeteorCutscene_Text8:
    ramcoord $01, $06
          ;XXXXXXXXXXXXXXXXXXXX
    text2 "Mais il doit être"
    line  "quelque part, je"
    line  "le sais..."
    done

MeteorCutscene_Text9:
    ramcoord $02, $08
          ;XXXXXXXXXXXXXXXXXXXX
    text2 "Je vais le"
    line  "retrouver!"
    done
