
BlankName::
	text2 "    "
	line

BallotName::
	text2 "B a l l o t"
	line

BuckName::
	text2 "B u c k"
	line

NinaName::
	text2 "N i n a"
	line

ClaudeName::
	text2 "C l a u d e"
	line

HelenName::
	text2 "H e l e n"
	line

LanteName::
	text2 "L a n t e"
	line

RandtName::
	text2 "R a n d t"
	line

MittName::
	text2 "M i t t"
	line

SnowyName::
	text2 "F l o c o n"
	line

text_0a_46f6::
	text2 "B e a t t r o"
	line

text_0a_46fd::
	text2 "E l e c t r e e p"
	line

text_0a_4703::
	text2 "C h r o m a n i x"
	line

text_0a_4709::
	text2 "M e r l i t h"
	line

text_0a_470e::
	text2 "M u s e r o d e"
	line

text_0a_4715::
	text2 "S i g n a l i t o n"
	line

text_0a_471b::
	text2 "D r a w v i l e"
	line

text_0a_4720::
    text2 "S a y a"
	line

text_0a_4727::
	text2 "H a y a t o"
	line

text_0a_472e::
	text2 "F a n g f a n g"
	line

text_0a_4735::
	text2 "N i c o l e"
	line

text_0a_473c::
	text2 "M r .   M o"
	line

text_0a_4742::
	text2 "P r i n c i p a l"
	line

text_0a_4749::
	text2 "M o n s t e r"
	line

text_0a_4750::
	text2 "      "
	line

text_0a_4757::
	text2 "O w n e r"
	line

text_0a_475e::
	text2 "I n a"
	line

text_0a_4765::
	text2 "Q u i t o"
	line

text_0a_476c::
	text2 "L e o"
	line

text_0a_4773::
	text2 "D o t"
	line

text_0a_477a::
	text2 "L a k i"
	line

text_0a_4781::
	text2 "K u l u"
	line

text_0a_4788::
	text2 "C o m p u t e r"
	line

text_0a_478e::
	text2 "C a t"
	line

text_0a_4795::
	text2 "V o l t   G r u n t"
	line

text_0a_479c::
	text2 "B u r t"
	line

text_0a_47a3::
	text2 "D i e p"
	line

text_0a_47aa::
	text2 "M a r k"
	line

text_0a_47b1::
	text2 "E l e c t r e e p"
	line

text_0a_47b7::
	text2 "C a u n f e e"
	line

text_0a_47bd::
	text2 "H a r r i s o n"
	line

text_0a_47c3::
	text2 "T y m e r"
	line

text_0a_47ca::
	text2 "B l a c k s u i t"
	line

text_0a_47d3::
	text2 "B a b e"
	line

text_0a_47da::
	text2 "M a s k e d m a n"
	line

text_0a_47e1::
	text2 "M t n P i g"
	line

text_0a_47e8::
	text "鴿", 7
	text " ", 0
	text "子", 0
	line

text_0a_47ef::
	text "兔", 3
	text "先", 0
	text "生", 1
	line

text_0a_47f6::
	text "石", 0
	text "兔", 3
	text "子", 0
	line

text_0a_47fd::
	text "胖", 7
	text " ", 0
	text "貓", 3
	line

text_0a_4804::
	text "石", 0
	text "山", 3
	text "豬"
	line

text_0a_480a::
	text "火", 0
	text "山", 3
	text "怪", 1
	line

text_0a_4811::
	text "兔", 3
	text "小", 0
	text "姐", 5
	line

text_0a_4818::
	text "麗", 6
	text " ", 0
	text "子", 0
	line

text_0a_481f::
	text2 "J u d g e s"
	line

text_0a_4826::
	text "主", 1
	text "持", 6
	text "人", 0
	line

text_0a_482d::
	text "哈", 3
	text "瑪", 6
	text "斯", 1
	line

text_0a_4834::
	text2 "A n t o n"
	line

text_0a_483b::
	text "烏", 5
	text " ", 0
	text "龜", 3
	line

text_0a_4842::
	text "螃", 7
	text " ", 0
	text "蟹", 3
	line

text_0a_4849::
	text "蝦", 7
	text " ", 0
	text "子", 0
	line

text_0a_4850::
	text2 "H a i q i n g"
	line

text_0a_4857::
	text "海", 0
	text "巫", 7
	text "師", 2
	line

text_0a_485e::
	text2 "U n k n o w n"
	line

text_0a_4865::
	text "狼", 0
	text "人"
	text "怪", 1
	line

text_0a_486b::
	text "星", 0
	text " ", 0
	text "獸", 1
	line

text_0a_4872::
	text "魚", 1
	text "之", 0
	text "魂"
	line

text_0a_4878::
	text "蒂", 7
	text " ", 0
	text "朵", 6
	line

text_0a_487f::
	text "老", 2
	text " ", 0
	text "鼠", 3
	line

text_0a_4886::
	text "邪", 0
	text "火"
	text "怪", 1
	line

text_0a_488c::
	text "吉", 4
	text "魯", 5
	text "德", 6
	line

text_0a_4893::
	text "白", 2
	text "蟻", 3
	text "怪", 1
	line

text_0a_489a::
	text "卡", 7
	text " ", 0
	text "爾", 5
	line

text_0a_48a1::
	text "卡", 7
	text "迪"
	text "拉", 5
	line

text_0a_48a7::
	text "謝", 5
	text "麗", 6
	text "娜", 5
	line

text_0a_48ae::
	text "分", 0
	text "析", 7
	text "儀", 1
	line

text_0a_48b5::
	text "雪", 0
	text " ", 0
	text "熊", 3
	line

text_0a_48bc::
	text "貝", 4
	text " ", 0
	text "爾", 5
	line

text_0a_48c3::
	text "教", 3
	text " ", 0
	text "授", 7
	line

text_0a_48ca::
	text "薦", 7
	text " ", 0
	text "拉", 5
	line

text_0a_48d1::
	text "龍", 1
	text "魔"
	text "人", 0
	line

text_0a_48d7::
	text "水", 0
	text "魔", 1
	text "人", 0
	line

text_0a_48de::
	text "火", 0
	text "魔", 1
	text "人", 0
	line

text_0a_48e5::
	text "徽", 3
	text "罰"
	text "者", 2
	line

text_0a_48eb::
	text "姆", 3
	text " ", 0
	text "斯", 1
	line

text_0a_48f2::
	text "帕", 7
	text " ", 0
	text "達", 1
	line

text_0a_48f9::
	text "仔", 4
	text " ", 0
	text "仔", 4
	line

text_0a_4900::
	text "諾", 5
	text " ", 0
	text "克", 4
	line

text_0a_4907::
	text "媞", 8
	text " ", 0
	text "雅", 6
	line

text_0a_490e::
	text "瑪", 6
	text " ", 0
	text "姬", 9
	line

text_0a_4915::
	text "管", 3
	text " ", 0
	text "家", 3
	line

text_0a_491c::
	text "艾", 5
	text " ", 0
	text "斯", 1
	line
