#!/usr/bin/env python3
"""Generate the VWF advance-width table from english_vwf.png.

Single source of truth for glyph widths: each glyph is left-flush, so the advance
width = (rightmost ink column + 1) + GAP. Space ($00) and any blank/undefined cell
default to SPACE_WIDTH. Output is an rgbasm byte table `VWFWidths::` indexed by the
`english` charmap code (code == tile/cell index), padded to all 256 codes so an
out-of-range byte can never read past the table.

Usage: python3 utils/vwf/gen_widths.py
Regenerate whenever lang_en/gfx/character_set/english_vwf.png changes.
"""
import os
from PIL import Image

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
VWF_PNG = os.path.join(REPO, "lang_en/gfx/character_set/english_vwf.png")
OUT = os.path.join(REPO, "lang_en/gfx/character_set/english_vwf_widths.asm")

GAP = 1           # blank columns after a glyph's ink
SPACE_WIDTH = 3   # advance for space / blank / undefined cells


def glyph_widths():
    im = Image.open(VWF_PNG).convert("L")
    px = im.load()
    widths = []
    for code in range(256):
        cx, cy = (code % 16) * 8, (code // 16) * 8
        maxx = -1
        for ry in range(8):
            for rx in range(8):
                if px[cx + rx, cy + ry] < 128:  # dark = ink
                    if rx > maxx:
                        maxx = rx
        w = (maxx + 1 + GAP) if maxx >= 0 else SPACE_WIDTH
        widths.append(w if w > 0 else SPACE_WIDTH)
    widths[0] = SPACE_WIDTH  # code $00 = space
    return widths


def main():
    widths = glyph_widths()
    lines = [
        "; AUTO-GENERATED by utils/vwf/gen_widths.py from english_vwf.png -- do not edit by hand.",
        "; VWF glyph advance widths in pixels, indexed by the `english` charmap code.",
        "; Regenerate after changing english_vwf.png.",
        "VWFWidths::",
    ]
    for i in range(0, 256, 16):
        row = ", ".join("$%02x" % w for w in widths[i:i + 16])
        lines.append("\tdb " + row)
    # write CRLF to match repo convention (every repo file is CRLF)
    with open(OUT, "w", newline="") as f:
        f.write("\r\n".join(lines) + "\r\n")
    nonblank = sum(1 for w in widths if w != SPACE_WIDTH)
    print("wrote %s (256 entries, %d non-default)" % (OUT, nonblank))


if __name__ == "__main__":
    main()
