MeteorCutscene_Text1:
    ramcoord $01, $08 ; string placement <X> <Y>
    text2 "[Harusnya saya"
    line  "sudah tahu.["
    done

MeteorCutscene_Text2:
    ramcoord $01, $06
    text2 "Itu kata-kata"
    line  "terakhir yang ku-"
    line  "dengar dari Ayah,"
    done

MeteorCutscene_Text3:
    ramcoord $01, $07
          ;XXXXXXXXXXXXXXXXXXXX
    text2 "sebelum dia pergi..."
    done

MeteorCutscene_Text4:
    ramcoord $01, $08 ; string placement <X> <Y>
          ;XXXXXXXXXXXXXXXXXXXX
    text2 "Esok paginya..."
    done

MeteorCutscene_Text5:
    ramcoord $01, $07
          ;XXXXXXXXXXXXXXXXXXXX
    text2 "Observatorium Ayah"
    line  "telah hancur."
    done

MeteorCutscene_Text6:
    ramcoord $01, $07
          ;XXXXXXXXXXXXXXXXXXXX
    text2 "Tidak ada yang tahu"
    line  "secara pasti apa"
    line  "yang terjadi,"
    done

MeteorCutscene_Text7:
    ramcoord $01, $07
          ;XXXXXXXXXXXXXXXXXXXX
    text2 "dan mereka pun tak"
    line  "pernah melihat Ayah"
    line  "lagi."
    done

MeteorCutscene_Text8:
    ramcoord $01, $06
          ;XXXXXXXXXXXXXXXXXXXX
    text2 "Tapi aku tahu, dia"
    line  "pasti masih ada..."
    done

MeteorCutscene_Text9:
    ramcoord $02, $08
          ;XXXXXXXXXXXXXXXXXXXX
    text2 "   Aku akan"
    line  " mencari Ayah!"
    done
