MeteorCutscene_Text1:
    ramcoord $01, $08 ; string placement <X> <Y>
    text2 "[I should've known.["
    done

MeteorCutscene_Text2:
    ramcoord $01, $06
    text2 "That was the last"
    line  "thing I heard Dad"
    line  "say,"
    done

MeteorCutscene_Text3:
    ramcoord $01, $07
    text2 "before he ran"
    line  "off..."
    done

MeteorCutscene_Text4:
    ramcoord $01, $08 ; string placement <X> <Y>
    text2 "The next morning.."
    done

MeteorCutscene_Text5:
    ramcoord $01, $07
    text2 "Dad's observatory"
    line  "was in ruins."
    done

MeteorCutscene_Text6:
    ramcoord $01, $07
    text2 "No one knew for"
    line  "sure what had"
    line  "happened,"
    done

MeteorCutscene_Text7:
    ramcoord $01, $07
    text2 "nor did they ever"
    line  "see Dad again."
    done

MeteorCutscene_Text8:
    ramcoord $01, $06
    text2 "But I know, that"
    line  "Dad must be"
    line  "somewhere in the"
    line  "world..."
    done

MeteorCutscene_Text9:
    ramcoord $02, $08
    text2 "I will find Dad!"
    done
